# Generated by Django 4.2.7 on 2024-06-07 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulter',
            name='image',
            field=models.ImageField(default='consulter/images/default.jpg', upload_to='consulter/images/'),
        ),
        migrations.RemoveField(
            model_name='consulter',
            name='available_time',
        ),
        migrations.AddField(
            model_name='consulter',
            name='available_time',
            field=models.ManyToManyField(to='consulter.availabletime'),
        ),
    ]
