# Generated by Django 4.2.7 on 2024-06-07 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0002_alter_client_user'),
        ('consulter', '0003_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appinment_types', models.CharField(choices=[('offline', 'offline'), ('online', 'online')], max_length=10)),
                ('appinment_status', models.CharField(choices=[('Completed', 'Completed'), ('Pending', 'Pending'), ('Running', 'Running')], default='Pending', max_length=10)),
                ('symptom', models.TextField()),
                ('cancel', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.client')),
                ('consulter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consulter.consulter')),
                ('time', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='consulter.availabletime')),
            ],
        ),
    ]
